name: rx-practice
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: configs/Debug.xcconfig
  Release: configs/Release.xcconfig
options:
  developmentLanguage: ja
settingGroups:
  rxPractice:
    CODE_SIGN_STYLE: Manual
    SWIFT_VERSION: 5.3
    TARGETED_DEVICE_FAMILY: "1"
    OTHER_LINKER_FLAGS: $(inherited) -ObjC
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    PRODUCT_BUNDLE_IDENTIFIER: rx-practice.${CONFIGURATION}
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  rxPracticeSettings:
    CODE_SIGN_STYLE: Automatic
    LD_RUNPATH_SEARCH_PATHS: ${inherited} @executable_path/Frameworks @loader_path/Frameworks
    PRODUCT_BUNDLE_IDENTIFIER: rx-practice.${PRODUCT_NAME}
targets:
  rx-practice:
    type: application
    platform: iOS
    scheme: {}
    deploymentTarget: "13.0"
    sources:
      - rx-practice
      - path: "rx-practice/Resources/R.generated.swift"
        optional: true
        type: file
    settings:
      groups: [rxPracticeSettings]
    dependencies:
      - target: Datasource
      - carthage: Action
      - carthage: Nuke
      - carthage: Reusable
      - carthage: Rswift
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: RxSwift
      - carthage: RxSwiftExt
      - carthage: SwiftyUserDefaults
      - carthage: PKHUD
      - carthage: Unio
    preBuildScripts:
      - script: |
                if mint list | grep -q 'R.swift'; then
                    mint run R.swift rswift generate "$SRCROOT/rx-practice/Resources/R.generated.swift"
                else
                    echo "error: R.swift not installed; run 'mint bootstrap' to install"
                    return -1
                fi
        name: Generate resources with R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - ${PRODUCT_NAME}/Resources/R.generated.swift
      - script: |
                if mint list | grep -q 'LicensePlist'; then
                    mint run mono0926/LicensePlist license-plist --output-path ${PRODUCT_NAME}/Resources/Settings.bundle
                else
                    echo "error: LicensePlist not installed. run 'mint bootstrap' to install"
                    return -1
                fi
        name: Run license-plist
    postBuildScripts:
      - script: mint run SwiftLint swiftlint
        name: Run SwiftLint
  Datasource:
    type: framework
    platform: iOS
    scheme: {}
    deploymentTarget: "13.0"
    sources:
      - Datasource
    settings:
      groups: [rxPracticeSettings]
    dependencies:
      - carthage: APIKit